# Generated by Django 3.2.6 on 2021-10-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetworkapp', '0002_auto_20211003_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Haha'), (1, 'Heart'), (3, 'Wow'), (0, 'Like')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
