# Generated by Django 3.2.6 on 2021-08-18 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetworkapp', '0004_auto_20210818_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_post', related_query_name='like_post', to='socialnetworkapp.post'),
        ),
    ]
