# Generated by Django 3.2.6 on 2021-08-18 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetworkapp', '0007_alter_post_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='created',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='updated',
            new_name='updated_date',
        ),
    ]
