# Generated by Django 3.2.6 on 2021-09-11 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetworkapp', '0014_user_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='active',
        ),
    ]
