# Generated by Django 3.2.6 on 2021-09-18 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetworkapp', '0016_alter_post_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='creator',
        ),
    ]
