# Generated by Django 3.2.6 on 2021-09-28 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetworkapp', '0018_auto_20210927_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='user',
            new_name='creator',
        ),
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Heart'), (3, 'Wow'), (2, 'Haha'), (0, 'Like')], default=0),
        ),
    ]
