# Generated by Django 3.2.6 on 2021-09-29 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetworkapp', '0019_auto_20210928_0839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='creator',
        ),
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Like'), (2, 'Haha'), (3, 'Wow'), (1, 'Heart')], default=0),
        ),
    ]
