# Generated by Django 3.2.6 on 2021-09-29 04:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetworkapp', '0021_auto_20210929_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Like'), (2, 'Haha'), (1, 'Heart'), (3, 'Wow')], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
