# Generated by Django 3.2.6 on 2021-09-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetworkapp', '0024_auto_20210929_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Wow'), (2, 'Haha'), (1, 'Heart'), (0, 'Like')], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
    ]
