# Generated by Django 3.2.6 on 2021-09-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetworkapp', '0027_auto_20210929_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Wow'), (2, 'Haha'), (0, 'Like'), (1, 'Heart')], default=0),
        ),
    ]
