# Generated by Django 3.2.6 on 2021-09-29 10:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetworkapp', '0028_auto_20210929_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Heart'), (0, 'Like'), (3, 'Wow'), (2, 'Haha')], default=0),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/auction_items/%Y/%m', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
    ]
