# Generated by Django 3.2.6 on 2021-09-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetworkapp', '0029_auto_20210929_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionitem',
            name='user_sell',
        ),
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Haha'), (1, 'Heart'), (0, 'Like'), (3, 'Wow')], default=0),
        ),
    ]
