# Generated by Django 3.2.6 on 2021-09-29 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetworkapp', '0030_auto_20210929_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionitem',
            name='description',
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_sell_item', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Wow'), (1, 'Heart'), (2, 'Haha'), (0, 'Like')], default=0),
        ),
    ]
