# Generated by Django 3.2.6 on 2021-09-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetworkapp', '0032_auto_20210929_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Heart'), (2, 'Haha'), (0, 'Like'), (3, 'Wow')], default=0),
        ),
    ]
