# Generated by Django 3.2.6 on 2021-09-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetworkapp', '0034_alter_action_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='liked',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Haha'), (0, 'Like'), (3, 'Wow'), (1, 'Heart')], default=0),
        ),
    ]
