# Generated by Django 3.2.6 on 2021-09-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetworkapp', '0036_auto_20210930_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Wow'), (2, 'Haha'), (0, 'Like'), (1, 'Heart')], default=0),
        ),
    ]
