# Generated by Django 3.2.6 on 2021-09-30 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetworkapp', '0037_alter_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Heart'), (2, 'Haha'), (0, 'Like'), (3, 'Wow')], default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='socialnetworkapp.post'),
        ),
    ]
