# Generated by Django 3.2.6 on 2021-10-01 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetworkapp', '0038_auto_20210930_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='items',
            new_name='item',
        ),
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Heart'), (3, 'Wow'), (0, 'Like'), (2, 'Haha')], default=0),
        ),
    ]
