# Generated by Django 3.2.6 on 2021-10-01 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetworkapp', '0039_auto_20211001_0812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='user_create_report',
            new_name='creator',
        ),
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Haha'), (3, 'Wow'), (1, 'Heart'), (0, 'Like')], default=0),
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('creator', 'user_is_reported')},
        ),
    ]
