# Generated by Django 3.2.6 on 2021-10-01 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetworkapp', '0040_auto_20211001_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateTimeField(blank=True, default=None, verbose_name='%d/%m/%Y'),
        ),
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Wow'), (0, 'Like'), (1, 'Heart'), (2, 'Haha')], default=0),
        ),
    ]
