# Generated by Django 3.2.6 on 2021-10-01 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetworkapp', '0041_auto_20211001_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
